import { createHash } from "node:crypto";
import { access, copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import {
  COMPOSE_TEMPLATE,
  ENV_RENDER_ORDER,
  REQUIRED_ENV_KEYS,
} from "./constants.js";
import type { EnvConfig, InstallState, RuntimeLayout } from "./types.js";

export function resolveInstallRoot(): string {
  const override = process.env.SEEDAR_INSTALL_DIR?.trim();
  if (override) {
    return path.resolve(override);
  }

  return path.join(os.homedir(), ".seedar");
}

export function toDockerPath(targetPath: string): string {
  return path.resolve(targetPath).replace(/\\/g, "/");
}

export function getRuntimeLayout(): RuntimeLayout {
  const installRoot = resolveInstallRoot();
  const instanceId = createHash("sha256")
    .update(installRoot)
    .digest("hex")
    .slice(0, 8);

  return {
    installRoot,
    runtimeDir: path.join(installRoot, "runtime"),
    dataDir: path.join(installRoot, "data"),
    mysqlDataDir: path.join(installRoot, "data", "mysql"),
    logsDir: path.join(installRoot, "logs"),
    backupsDir: path.join(installRoot, "backups"),
    composePath: path.join(installRoot, "runtime", "docker-compose.yml"),
    envPath: path.join(installRoot, "runtime", ".env"),
    versionPath: path.join(installRoot, "runtime", ".installed-version"),
    statePath: path.join(installRoot, "runtime", ".install-state"),
    instanceId,
    projectName: `seedar-${instanceId}`,
  };
}

export async function pathExists(targetPath: string): Promise<boolean> {
  try {
    await access(targetPath);
    return true;
  } catch {
    return false;
  }
}

export async function ensureRuntimeDirectories(layout: RuntimeLayout): Promise<void> {
  await mkdir(layout.runtimeDir, { recursive: true });
  await mkdir(layout.dataDir, { recursive: true });
  await mkdir(layout.mysqlDataDir, { recursive: true });
  await mkdir(layout.logsDir, { recursive: true });
  await mkdir(layout.backupsDir, { recursive: true });
}

export function renderEnvFile(env: EnvConfig): string {
  const lines: string[] = [
    "# Generated by seedar CLI",
    "# Edit with care. Use `seedar update` to change versions safely.",
    "",
  ];

  for (const key of ENV_RENDER_ORDER) {
    const value = env[key];
    lines.push(`${key}=${value}`);
  }

  lines.push("");
  return lines.join("\n");
}

export function parseEnvFile(content: string): Record<string, string> {
  const result: Record<string, string> = {};

  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }

    const index = line.indexOf("=");
    if (index === -1) {
      continue;
    }

    const key = line.slice(0, index).trim();
    const value = line.slice(index + 1).trim();
    result[key] = value;
  }

  return result;
}

export function assertEnvShape(env: Record<string, string>): EnvConfig {
  const missing = REQUIRED_ENV_KEYS.filter((key) => !env[key]);
  if (missing.length > 0) {
    throw new Error(`运行时配置缺少字段: ${missing.join(", ")}`);
  }

  return env as unknown as EnvConfig;
}

export async function readEnvConfig(layout: RuntimeLayout): Promise<EnvConfig> {
  const content = await readFile(layout.envPath, "utf8");
  return assertEnvShape(parseEnvFile(content));
}

export async function writeRuntimeFiles(
  layout: RuntimeLayout,
  env: EnvConfig,
): Promise<void> {
  await ensureRuntimeDirectories(layout);
  await writeFile(layout.composePath, COMPOSE_TEMPLATE, "utf8");
  await writeFile(layout.envPath, renderEnvFile(env), "utf8");
}

export async function writeInstalledVersion(
  layout: RuntimeLayout,
  version: string,
): Promise<void> {
  await writeFile(layout.versionPath, `${version}\n`, "utf8");
}

export async function readInstalledVersion(
  layout: RuntimeLayout,
): Promise<string | null> {
  if (!(await pathExists(layout.versionPath))) {
    return null;
  }

  const content = await readFile(layout.versionPath, "utf8");
  return content.trim() || null;
}

export async function writeInstallState(
  layout: RuntimeLayout,
  state: InstallState,
): Promise<void> {
  await writeFile(layout.statePath, `${state}\n`, "utf8");
}

export async function readInstallState(
  layout: RuntimeLayout,
): Promise<InstallState> {
  if (!(await pathExists(layout.statePath))) {
    const hasRuntime =
      (await pathExists(layout.composePath)) && (await pathExists(layout.envPath));
    return hasRuntime ? "installed" : "unknown";
  }

  const content = await readFile(layout.statePath, "utf8");
  const normalized = content.trim();
  if (normalized === "installed" || normalized === "uninstalled") {
    return normalized;
  }

  return "unknown";
}

export async function hasRuntimeConfig(layout: RuntimeLayout): Promise<boolean> {
  return (await pathExists(layout.composePath)) && (await pathExists(layout.envPath));
}

export async function backupRuntime(layout: RuntimeLayout): Promise<string> {
  await ensureRuntimeDirectories(layout);

  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupDir = path.join(layout.backupsDir, stamp);
  await mkdir(backupDir, { recursive: true });

  const files: Array<[string, string]> = [
    [layout.envPath, path.join(backupDir, ".env")],
    [layout.composePath, path.join(backupDir, "docker-compose.yml")],
    [layout.versionPath, path.join(backupDir, ".installed-version")],
    [layout.statePath, path.join(backupDir, ".install-state")],
  ];

  for (const [source, target] of files) {
    if (await pathExists(source)) {
      await copyFile(source, target);
    }
  }

  return backupDir;
}

export function buildDefaultEnv(
  layout: RuntimeLayout,
  values: Omit<EnvConfig, "SEEDAR_INSTALL_ROOT" | "SEEDAR_INSTANCE_ID" | "SEEDAR_PROJECT_NAME">,
): EnvConfig {
  return {
    ...values,
    SEEDAR_INSTALL_ROOT: toDockerPath(layout.installRoot),
    SEEDAR_INSTANCE_ID: layout.instanceId,
    SEEDAR_PROJECT_NAME: layout.projectName,
  };
}

export async function restoreRuntimeFromBackup(
  layout: RuntimeLayout,
  backupDir: string,
): Promise<void> {
  const files: Array<[string, string]> = [
    [path.join(backupDir, ".env"), layout.envPath],
    [path.join(backupDir, "docker-compose.yml"), layout.composePath],
    [path.join(backupDir, ".installed-version"), layout.versionPath],
    [path.join(backupDir, ".install-state"), layout.statePath],
  ];

  for (const [source, target] of files) {
    if (await pathExists(source)) {
      await copyFile(source, target);
    }
  }
}
